id: opecha:P006943
initial_creation_type: ocr
source_metadata:
  id: bdr:W28965
  title: རྒྱལ་རོང་ཞིབ་འཇུག་དཔྱད་ཡིག་ཕྱོགས་བསྒྲིགས
  volume:
    3e135fb11a614b1bbc3643ca13ca18cb:
      image_group_id: I1GS58138
      title: Volume 1 of rgyal rong zhib 'jug dpyad yig phyogs bsgrigs
      volume_number: 1
      total_pages: 370
  author: ''
ebook_metadata:
  title: རྒྱལ་རོང་ཞིབ་འཇུག་དཔྱད་ཡིག་ཕྱོགས་བསྒྲིགས
  author: ''
  sku: P006943
  cover: cover.jpg
  layers:
  - pagination
