id: P006943
initial_creation_type: ocr
source_metadata:
  id: bdr:W28965
  title: རྒྱལ་རོང་ཞིབ་འཇུག་དཔྱད་ཡིག་ཕྱོགས་བསྒྲིགས
  author: ''
  volumes:
    213ddd8703264182a039db0ea8b896c7:
      image_group_id: I1GS58138
      title: ''
      volume_number: 1
      total_pages: 370
ebook_metadata:
  title: རྒྱལ་རོང་ཞིབ་འཇུག་དཔྱད་ཡིག་ཕྱོགས་བསྒྲིགས
  author: ''
  sku: P006943
  cover: cover.jpg
  layers:
  - pagination
